# Generated by Django 2.2.5 on 2019-09-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('link', models.URLField()),
            ],
        ),
    ]
